version: 0.0
os: linux
files:
  - source: /dist/terminus-clinical-summary/assets
    destination: /var/www/interneuron-terminus/assets
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_service.sh
      timeout: 300
      runas: root
